import { convertFromRaw, EditorState } from "draft-js";
import Head from "next/head";
import Link from "next/link";
import { useQuery } from "urql";

import { MenuBar } from "../components/menuBar";
import { Posts } from "../components/posts";
import { POST_QUERY } from "../graphql/queries";
import { client, ssrCache } from "../urqlClient";

export default function Home() {
  const [result] = useQuery({
    query: POST_QUERY,
  });
  const { data, fetching, error } = result;

  if (fetching) return "loading";
  if (error) {
    console.log(error);
  }
  let a = data ? "sddfs" : "sdfds";
  return (
    <div>
      <Head>
        <title>TAA</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://i.ibb.co/6ns5q9k/apollo-god-of-sun-symbol-logo-trademark-antelope-wildlife-transparent-png-1515689-removebg-preview.png"
        />
      </Head>
      <MenuBar />

      {data.getPosts &&
        data.getPosts.map((post) => {
          const contentState = convertFromRaw(JSON.parse(post.body));
          const state = EditorState.createWithContent(contentState);

          return (
            // eslint-disable-next-line react/jsx-key
            <Posts post={post} />
          );
        })}
    </div>
  );
}

// export async function getServerSideProps() {
//   await client.query(POST_QUERY).toPromise();
//   return {
//     props: {
//       urqlState: ssrCache.extractData(),
//     },
//   };
// }
